# Generated by Django 4.2.5 on 2023-10-12 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KaoShi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a", models.CharField(max_length=50)),
                ("other", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TiKu_pdt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t", models.CharField(max_length=300)),
                ("a", models.CharField(max_length=4)),
                ("b", models.CharField(max_length=4)),
                ("daan", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="TiKu_xzt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t", models.CharField(max_length=300)),
                ("a", models.CharField(max_length=100)),
                ("b", models.CharField(max_length=100)),
                ("c", models.CharField(max_length=100)),
                ("d", models.CharField(max_length=100)),
                ("daan", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="TiKu_xzt1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t", models.CharField(max_length=300)),
                ("a", models.CharField(max_length=100)),
                ("b", models.CharField(max_length=100)),
                ("c", models.CharField(max_length=100)),
                ("daan", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="ChengJi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_user", models.IntegerField()),
                ("key_KaoShi", models.IntegerField()),
                (
                    "keu_KaoShi_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.kaoshi"
                    ),
                ),
                (
                    "key_user_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.useraccount",
                    ),
                ),
            ],
        ),
    ]
