# Generated by Django 4.2.5 on 2023-10-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_kaoshi_tiku_pdt_tiku_xzt_tiku_xzt1_chengji"),
    ]

    operations = [
        migrations.RemoveField(model_name="chengji", name="key_KaoShi",),
        migrations.RemoveField(model_name="chengji", name="key_user",),
        migrations.AddField(
            model_name="chengji",
            name="fenshu",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
