# Generated by Django 4.2.5 on 2023-10-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_remove_chengji_key_kaoshi_remove_chengji_key_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kaoshi",
            name="img",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
